"""Source-linked human-made antecedent; never an AI output or claimed prompt origin."""
import html

HISTORY_ID = 'roger-rabbit-1988-75a07f88'
FILM_SOURCE = 'https://simonwillison.net/2026/Sep/18/the-creative-spirit-of-who-framed-roger-rabbit/'
MAKING_SOURCE = 'https://blog.cypressf.com/post/828067789747208192/the-creative-spirit-of-who-framed-roger-rabbit'
ANIMATOR_SOURCE = 'https://andreasdeja.blogspot.com/2016/02/roger-rabbit-scenes.html'
AI_ORIGIN = 'https://simonwillison.net/2024/Oct/25/pelicans-on-a-bicycle/'


def historical_display(item, language='zh'):
    """A presentation copy; archive title, notes, date and media stay untouched."""
    if item['id'] != HISTORY_ID:
        return item
    display = dict(item)
    if language == 'en':
        display.update(title='1988 · A pelican on a bicycle before AI',
                       notes='The pelican postman in Who Framed Roger Rabbit combines a hand-drawn character with a real bicycle. This human-made historical antecedent retains the film clip and links practical-effects accounts and an animator’s recollection. It is not an AI output, and no checked source establishes it as the inspiration for the 2024 SVG test.',
                       promptStatus='Not applicable: human-made film footage, not an AI prompt output.')
    else:
        display.update(title='1988 · AI 之前，鹈鹕已经骑上了车',
                       notes='《谁陷害了兔子罗杰》中的鹈鹕邮差：手绘角色骑上真实自行车。这份人类创作的历史前例保留电影片段，并连接实拍特效与动画师回忆；它不是 AI 输出，也没有证据证明它启发了 2024 年的 SVG 测试。',
                       promptStatus='不适用：人类制作的电影镜头，非 AI 提示词输出。')
    return display


def historical_sections(language='zh'):
    if language == 'en':
        return [
            ('1988 · A pelican before AI', 'In Robert Zemeckis’s Who Framed Roger Rabbit, a hand-drawn pelican postman rides a real bicycle through the studio lot. This is human-made cinema, not a model output. It is an earlier example we have documented, not a claim that no earlier depiction exists.', FILM_SOURCE, 'Simon’s film clip and context'),
            ('How did a riderless bicycle move?', 'Cypress Frankenfeld cites a Cinefex interview: Michael Lantieri’s effects crew filled the tyres with water to help balance and momentum, then guided the bicycle with a cable. The filmed prop and animated rider were combined; the bicycle was not generated by AI.', MAKING_SOURCE, 'The practical-effects account'),
            ('The people behind the pelican', 'Animator Andreas Deja recalls the long studio-lot sequence and credits the pelican section to Dave Spafford. The character loses control and crashes, with mail scattering around him. This recollection distinguishes the animation work from the physical bicycle effect.', ANIMATOR_SOURCE, 'Andreas Deja’s 2016 recollection'),
            ('2024 · The AI test begins', 'Simon Willison published his SVG test on October 25, 2024. He said he liked pelicans and wanted a subject unlikely to have existing SVG examples in training data. No checked source establishes the 1988 film as his inspiration. The film is a historical antecedent, not the documented cause of the AI prompt.', AI_ORIGIN, 'Read the original 2024 experiment'),
            ('Two dates, different meanings', '1988 is the film year, with year-only precision. The clip’s source post is dated September 18, 2026; that later discussion is not a new creation date. This historical record stays accessible but does not add an AI work, a model-release position or a museum case number.', FILM_SOURCE, 'Check the dated source post'),
        ]
    return [
        ('1988 · AI 之前，鹈鹕已经骑上了车', '在 Robert Zemeckis 执导的《谁陷害了兔子罗杰》中，手绘的鹈鹕邮差骑着真实自行车穿过摄影棚街区。这是人类制作的电影画面，不是模型输出。它是本馆已核实的早期实例，不据此宣称世上没有更早的描绘。', FILM_SOURCE, 'Simon 保存的电影片段与说明'),
        ('没有骑手，自行车如何前进？', 'Cypress Frankenfeld 引用 Cinefex 采访介绍：Michael Lantieri 的特效团队给轮胎灌水，帮助自行车保持平衡和向前运动，再用牵引线引导路线。实拍道具与手绘角色组合成画面；自行车并非 AI 生成。', MAKING_SOURCE, '阅读实拍特效的制作说明'),
        ('这只鹈鹕背后的人', '动画师 Andreas Deja 回忆这段摄影棚长镜头时，将鹈鹕段落的动画署名归给 Dave Spafford。角色失控、摔倒，邮件散落四周；这份创作者回忆也让我们能区分角色动画与真实自行车特效的分工。', ANIMATOR_SOURCE, 'Andreas Deja 的 2016 年回忆'),
        ('2024 · AI 小题目的起点', 'Simon Willison 于 2024 年 10 月 25 日公开 SVG 测试。他解释选题是因为喜欢鹈鹕，并希望避免训练数据里已有同题 SVG。已核对的来源没有证明这部 1988 年电影启发了他的提示词；这里展示的是历史前例，而不是臆造一条因果链。', AI_ORIGIN, '阅读 2024 年原始实验'),
        ('两种日期，不是同一回事', '1988 是电影年份，只保留年精度；片段来源文章发表于 2026 年 9 月 18 日，后来的讨论不能当作新创作日。本历史记录保留详情与出处，但不增加 AI 作品数，不占型号发布位置，也没有主馆案例编号。', FILM_SOURCE, '核对片段来源的公开日期'),
    ]


def historical_story(language='zh'):
    e=lambda s:html.escape(str(s),quote=True)
    return '<section class="historical-story" data-historical-story>'+''.join('<section><h2>'+e(title)+'</h2><p>'+e(text)+'</p><p><a class="text-link" href="'+e(url)+'" target="_blank" rel="noopener noreferrer">'+e(label)+' ↗</a></p></section>' for title,text,url,label in historical_sections(language))+'</section>'


def historical_markdown(language='zh'):
    return '\n\n'+'\n\n'.join('## '+title+'\n\n'+text+'\n\n['+label+']('+url+')' for title,text,url,label in historical_sections(language))+'\n'


def historical_summary(language='zh'):
    return [('Film year','1988'),('Creation','Hand-drawn animation + live action; not AI'),('Pelican animation','Dave Spafford (credited in Andreas Deja’s account)'),('Archive status','Historical context; no AI case number')] if language=='en' else [('电影年份','1988'),('创作形式','手绘动画 + 实拍；非 AI'),('鹈鹕角色动画','Dave Spafford（据 Andreas Deja 回忆）'),('馆藏身份','历史前例；不占 AI 案例编号')]


def historical_hero(items, language='zh'):
    item=next(x for x in items if x['id']==HISTORY_ID)
    assert not item['caseVisible'] and not item['timelineVisible'] and item['caseNumber'] is None
    e=lambda s:html.escape(str(s),quote=True)
    en=language=='en'
    label='BEFORE AI / 1988' if en else 'AI 之前 / 1988'
    caption='A hand-drawn pelican. A real bicycle.' if en else '手绘鹈鹕，真实自行车。'
    title='Before AI, a pelican was already riding a bicycle' if en else 'AI 之前，鹈鹕已经骑上了车'
    media=item['media'][0]
    return '<figure class="hero-figure" data-historical-hero><span class="plate-no">'+label+'</span><a class="hero-media" href="'+e(item['path'])+'" aria-label="'+e(title)+'"><img class="cover" src="'+e(item['thumbnail'])+'" alt="'+e(title)+'" width="960" height="720" fetchpriority="high"><video class="motion-layer" data-motion-kind="video" data-motion-src="'+e(media['src'])+'" poster="'+e(media['poster'])+'" autoplay muted loop playsinline preload="none" aria-hidden="true" tabindex="-1"></video></a><figcaption><span>1988 · '+caption+'</span><a href="'+e(item['path'])+'">'+('Discover the story ↗' if en else '看看这段故事 ↗')+'</a></figcaption></figure>'
